---

id: Firecrown
# Python modules that are imported to find
# stage classes.  Any stages imported in these
# modules are automatically detected and their names can
# be used below
modules: clpipeline

# The launcher to use
# These are defined in ceci/sites
launcher:
    name: mini
    interval: 0.5

# launcher:
#   name: parsl
#   # max_threads only referenced for local sites
#   #log: parsl_log.txt

# launcher:
#     name: cwl
#     launcher: cwltool
#     dir: ./test/cwl

site:
    name: local
    max_threads: 4
  # max_threads: 4
  # container: joezuntz/txpipe
  # volume:  $PWD:/opt/txpipe



#site:
#    name: nersc-interactive
#    # Put the log for the overall pipeline infrastructure in this file:
#    pipeline_log: log.txt

# site:
#     name: nersc-batch
#     cpu_type: haswell
#     queue: debug
#     max_jobs: 2
#     account: m1727
#     walltime: "00:30:00"
#     setup: /global/projecta/projectdirs/lsst/groups/WL/users/zuntz/setup-cori



# The list of stages to run and the number of processors
# to use for each.
stages:
    - name: FirecrownPipeline
      module_name: clpipeline.firecrown_pipeline
      nprocess: 1

# Definitions of where to find inputs for the overall pipeline.
# Any input required by a pipeline stage that is not generated by
# a previous stage must be defined here.  They are listed by tag.
inputs:
    clusters_sacc_file: ${LOCAL_DIR}/data/inputs/dm.txt

# Overall configuration file 
config: ${LOCAL_DIR}/inputs_config_generic/config.yml

# If all the outputs for a stage already exist then do not re-run that stage
resume: False

# Put all the output files in this directory:
output_dir: ${OUTPUT_DIR}/tjpcov_firecrown

# Put the logs from the individual stages in this directory:
log_dir: ${OUTPUT_DIR}/tjpcov_firecrown/logs

---

id: TXPipe


---
id: TJPCov
# Python modules that are imported to find
# stage classes.  Any stages imported in these
# modules are automatically detected and their names can
# be used below
modules: clpipeline

# The launcher to use
# These are defined in ceci/sites
launcher:
    name: mini
    interval: 0.5
# launcher:
#   name: parsl
#   # max_threads only referenced for local sites
#   #log: parsl_log.txt

# launcher:
#     name: cwl
#     launcher: cwltool
#     dir: ./test/cwl

site:
    name: local
    max_threads: 4
  # max_threads: 4
  # container: joezuntz/txpipe
  # volume:  $PWD:/opt/txpipe



#site:
#    name: nersc-interactive
#    # Put the log for the overall pipeline infrastructure in this file:
#    pipeline_log: log.txt

# site:
#     name: nersc-batch
#     cpu_type: haswell
#     queue: debug
#     max_jobs: 2
#     account: m1727
#     walltime: "00:30:00"
#     setup: /global/projecta/projectdirs/lsst/groups/WL/users/zuntz/setup-cori



# The list of stages to run and the number of processors
# to use for each.
stages:
    - name: TJPCovPipeline
      module_name: clpipeline.tjpcov_pipeline
      nprocess: 1

# Definitions of where to find inputs for the overall pipeline.
# Any input required by a pipeline stage that is not generated by
# a previous stage must be defined here.  They are listed by tag.
inputs:
    clusters_sacc_file: ${LOCAL_DIR}/data/clusters_sacc_file.sacc

# Overall configuration file 
config: ${LOCAL_DIR}/inputs_config_generic/config.yml


# If all the outputs for a stage already exist then do not re-run that stage
resume: False

# Put all the output files in this directory:
output_dir: ${OUTPUT_DIR}/tjpcov_firecrown


# Put the logs from the individual stages in this directory:
log_dir: ${OUTPUT_DIR}/tjpcov_firecrown/logs

---