#this step depends on where you run
#for CCin2p3
site:
    name: local
    max_threads: 4
#site:
#    name: cori-batch
#    image: ghcr.io/lsstdesc/txpipe-dev
#all the following steps should not depend on where you run 
launcher:
    name: mini
    interval: 0.5
modules: 
    txpipe
    rail.estimation.algos.bpz_lite
python_paths: []
stages:
  - name: TXSourceSelectorMetadetect
    nprocess: 30
  - name: BPZliteInformer
    nprocess: 1
    aliases:
        input: spectroscopic_catalog
        model: photoz_model
  - name: BPZliteEstimator
    nprocess: 30
    aliases:
        model: photoz_model
        input: shear_catalog
        output: source_photoz_pdfs
  - name: CLClusterBinningRedshiftRichness
    nprocess: 1
  - name: CLClusterShearCatalogs
    nprocess: 30   #>1 does not work with mpi
  - name: CLClusterEnsembleProfiles
    nprocess: 10
#    - name: CLClusterDataVector
#      nprocess: 1

output_dir: ${OUTPUT_DIR}/cosmodc2/outputs-20deg2-CL

# Put the logs from the individual stages in this directory:
log_dir: ${OUTPUT_DIR}/logs/cosmodc2/outputs-20deg2-CL

# Put the logs from the individual stages in this directory:
config: ${CONFIG_YAML}

inputs:

resume: true
pipeline_log: ${OUTPUT_DIR}/cosmodc2/log_20deg2.txt

